In [2]:
import numpy as np

# Step 1: Generate a 3x4 random matrix
matrix_3x4 = np.random.randint(1, 21, size=(3, 4))  # Random integers from 1 to 20

# Split the matrix into A and b
A = matrix_3x4[:, :3]  # Coefficient matrix (first 3 columns)
b = matrix_3x4[:, 3]   # Right-hand side vector (last column)

# Display the matrices
print("Generated 3x4 Matrix:")
print(matrix_3x4)

print("\nCoefficient Matrix (A):")
print(A)

print("\nRight-hand Side Vector (b):")
print(b)


Generated 3x4 Matrix:
[[ 1  2  7  9]
 [19  6  9 12]
 [18  5 10 19]]

Coefficient Matrix (A):
[[ 1  2  7]
 [19  6  9]
 [18  5 10]]

Right-hand Side Vector (b):
[ 9 12 19]


In [3]:
# Solve using Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A)  # Compute A^-1
    x_manual = np.dot(A_inv, b)  # x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_manual)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")

# Solve using Gaussian Elimination
x_gaussian = np.linalg.solve(A, b)  # Direct Gaussian elimination
print("\nSolution using Gaussian Elimination (NumPy):")
print(x_gaussian)

# Verify the solution
b_check = np.dot(A, x_gaussian)  # Recompute b using A and the computed x
print("\nVerification (Ax = b):")
print(b_check)



Solution using Matrix Inverse Method:
[ 1.06818182 -5.39393939  2.67424242]

Solution using Gaussian Elimination (NumPy):
[ 1.06818182 -5.39393939  2.67424242]

Verification (Ax = b):
[ 9. 12. 19.]
